---
- hosts: APIServer
  become: yes
  tasks:
  - name: Make api folder
    file:
      path: /api
      state: directory

  - name: Installing packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - python3-pip
    - python3-virtualenv
    - git
    
  - name: Git clone repository
    git:
      repo: https://github.com/draw-and-deploy/api
      dest: /api
      clone: yes
      update: yes

  - name: Create directory for user scripts
    file:
      path: /drawanddeploy
      state: directory
      mode: 0733

  - name: Installing pip packages
    pip:
      name: "{{ item }}"
      state: present
      virtualenv: /api/venv
    with_items:
    - uvicorn
    - fastapi
    - gunicorn
    - boto3

  - name: Creating error files
    file:
      path: "{{ item }}"
      state: touch
      mode: "0733"
    with_items:
    - "/api/access_log"
    - "/api/error_log"

  - name: Creating gunicorn config file
    copy:
      src: /playbooks/files/gunicorn_config.py
      dest: /api/gunicorn_config.py
      mode: 0644

  - name: Creating gunicorn.service file
    copy:
      src: /playbooks/files/gunicorn.service
      dest: /etc/systemd/system/gunicorn.service        
      mode: 0644

  - name: Creating gunicorn.socket file
    copy:
      src: /playbooks/files/gunicorn.socket
      dest: /etc/systemd/system/gunicorn.socket
      mode: 0644
  
  - name: Enable socket
    service:
      name: gunicorn.socket
      state: restarted
      enabled: yes

  - name: Restart the gunicorn service 
    service:
      name: gunicorn.service
      state: restarted
      enabled: yes

  - name: Configuring reverse proxy on nginx
    copy:
      src: /playbooks/files/nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: Restarting nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
