---
- hosts: APIServer
  become: yes
  tasks:
  - name: Make api folder
    file:
      path: /api
      state: directory

  - name: Installing packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - python3-pip
    - python3-virtualenv
    - git

  - name: Git clone repository
    git:
      repo: https://github.com/draw-and-deploy/api
      dest: /api
      clone: yes
      update: yes

  - name: Installing pip packages
    pip:
      name: "{{ item }}"
      state: present
      virtualenv: /api/venv
    with_items:
    - fastapi
    - uvicorn
    - gunicorn

  - name: Creating error files
    file:
      path: "{{ item }}"
      state: touch
      mode: "0733"
    with_items:
    - "/api/access_log"
    - "/api/error_log"

  - name: Creating gunicorn config file
    copy:
      dest: "/api/gunicorn_config.py"
      content: |
        from multiprocessing import cpu_count

        # Socket Path
        bind = 'unix:/api/gunicorn.sock'

        # Worker Options
        workers = cpu_count() + 1
        worker_class = 'uvicorn.workers.UvicornWorker'

        # Logging Options
        loglevel = 'debug'
        accesslog = '/api/access_log'
        errorlog =  '/api/error_log'

  - name: Creating systemd file
    copy:
      dest: "/etc/systemd/system/api_dnd.service"
      content: |
        [Unit]
        Description=API para a tela de Drag and Drop
        After=network.target

        [Service]
        User=ubuntu
        WorkingDirectory=/api/
        ExecStart=/api/venv/bin/gunicorn -c gunicorn_config.py -b :8000 main:app
        Restart=always

        [Install]
        WantedBy=multi-user.target
  
