---
- hosts: APIServer
  become: yes
  tasks:
  - name: Make api folder
    file:
      path: /api
      state: directory

  - name: Installing packages
    package:
      name: ["python3-pip", "python3-virtualvenv", "git"]
      state: latest
    
  - name: Git clone repository
    git:
      repo: https://github.com/draw-and-deploy/api
      dest: /api
      clone: yes
      update: yes

  - name: Create directory for user scripts
    file:
      path: /terraform_api_dirs
      state: directory
      mode: 0733

  - name: Installing pip packages
    pip:
      name: ["fastapi", "uvicorn", "gunicorn"]
      state: present
      virtualenv: /api/venv
    
  - name: Creating error files
    file:
      path: ["/api/access_log", "/api/error_log"]
      state: touch
      mode: "0733"

  - name: Creating gunicorn config file
    copy:
      src: /playbooks/Config/gunicorn_config.py
      dest: /api/gunicorn_config.py
      mode: 0644

  - name: Creating systemd file
    copy:
      src: /playbooks/Config/api_dnd.service
      dest: /etc/systemd/system/api_dnd.service        
      mode: 0644
  
  - name: Restart the service 
    service:
      name: api_dnd
      state: restarted
      enabled: yes
